# Generated by Django 5.1.6 on 2025-02-11 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_events_event_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos_gallery',
            old_name='Videos',
            new_name='video',
        ),
    ]
