# Generated by Django 5.1.6 on 2025-02-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_videos_videos_gallery_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.EmailField(default='exit', max_length=200),
            preserve_default=False,
        ),
    ]
