# Generated by Django 5.1.6 on 2025-02-24 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_message_email_alter_message_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='phone_number',
        ),
    ]
