# Generated by Django 5.1.4 on 2025-01-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
    ]
