# Generated by Django 5.1.4 on 2025-01-17 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_game'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.AlterField(
            model_name='message',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')]),
        ),
    ]
